[phases.setup]
aptPkgs = ["python3", "python3-pip", "gunicorn", "uvicorn"]

[phases.install]
cmds = [
      "pip install --upgrade pip",
      "pip install --no-cache-dir -r backend/requirements.txt"
]

[start]
cmd = "gunicorn -w 4 -k uvicorn.workers.UvicornWorker backend.app:app"